services:
  backend:
    build:
      context: ./backend
    container_name: geoview-backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    working_dir: /app
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: geoview-frontend
    command: npm run dev -- --host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./frontend/.env
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
